### PR TITLE
Add NUnit and FluentAssertions

### PR DESCRIPTION
**Pull request by mtran45**

### CODE REVIEW

**Comment by mtran45** [comment]
Cool looks like the tests are running in CI and the failing test shows up here, which should prevent merging

**Comment by mtran45** [comment]
I'm going to look into setting up the code coverage report

**Review by kenash-dev — APPROVED** [review]
Raise another ticket for CI/CD set up.

**Comment by mtran45** [comment]
@kenash-dev Ok cool got code coverage results 
https://dev.azure.com/collaboration-inc/movie-seller/_build/results?buildId=16&view=results
Apparently we have 41.49% covered even though the tests don't actually cover anything 🤷‍♂️

**Pull request merged**
